sudo: required
services:
  - docker

before_install:
  - docker build -t deepkanwal/dku-docker-react -f Dockerfile.dev .
    
script:
  - docker run deepkanwal/dku-docker-react npm run test -- --coverage
